openapi: 3.0.0
info:
  title: Terra Cloud Resource UIDs
  description: |
    Terra Cloud Resources Library definitions of unique identifiers for cloud resources.
  version: 0.0.2

# This file defines component models to be reused, not a service path.
paths: {}

components:
  schemas:
    GoogleBigQueryDatasetUid:
      type: object
      required:
        - projectId
        - datasetId
      properties:
        projectId:
          type: string
        datasetId:
          type: string
    GoogleBigQueryTableUid:
      type: object
      required:
        - projectId
        - datasetId
        - tableId
      properties:
        projectId:
          type: string
        datasetId:
          type: string
        tableId:
          type: string
    GoogleBlobUid:
      type: object
      required:
        - bucketName
        - blobName
      properties:
        bucketName:
          type: string
        blobName:
          type: string
    GoogleBucketUid:
      type: object
      required:
        - bucketName
      properties:
        bucketName:
          type: string
    GoogleProjectUid:
      type: object
      required:
        - projectId
      properties:
        projectId:
          type: string
    # A cloud resource unique identifier. Each CloudResourceUid represents exactly one cloud resource.
    # We are not doing polymorphism at this moment because of lack of support in swagger-codegen or openApiGenerator
    # Now CloudResourceUid contains all possible cloud resource types, and we will assume there is only one being set
    # when using this.
    CloudResourceUid:
      type: object
      properties:
        googleProjectUid:
          $ref: '#/components/schemas/GoogleProjectUid'
        googleBigQueryDatasetUid:
          $ref: '#/components/schemas/GoogleBigQueryDatasetUid'
        googleBigQueryTableUid:
          $ref: '#/components/schemas/GoogleBigQueryTableUid'
        googleBlobUid:
          $ref: '#/components/schemas/GoogleBlobUid'
        googleBucketUid:
          $ref: '#/components/schemas/GoogleBucketUid'
