openapi: 3.0.0
info:
  title: Terra Cloud Resource UIDs
  description: |
    Terra Cloud Resources Library definitions of unique identifiers for cloud resources.
  version: 0.0.2

# This file defines component models to be reused, not a service path.
paths: {}

components:
  schemas:
    GoogleAiNotebookInstanceUid:
      type: object
      required:
        - projectId
        - location
        - instanceId
      properties:
        projectId:
          type: string
        location:
          type: string
          description: The location of the instance, e.g. 'uswest1-b'.
        instanceId:
          type: string
          description: The user-provided instance id to identify the instance.
    GoogleBigQueryDatasetUid:
      type: object
      required:
        - projectId
        - datasetId
      properties:
        projectId:
          type: string
        datasetId:
          type: string
    GoogleBigQueryTableUid:
      type: object
      required:
        - projectId
        - datasetId
        - tableId
      properties:
        projectId:
          type: string
        datasetId:
          type: string
        tableId:
          type: string
    GoogleBlobUid:
      type: object
      required:
        - bucketName
        - blobName
      properties:
        bucketName:
          type: string
        blobName:
          type: string
    GoogleBucketUid:
      type: object
      required:
        - bucketName
      properties:
        bucketName:
          type: string
    GoogleProjectUid:
      type: object
      required:
        - projectId
      properties:
        projectId:
          type: string
    AzurePublicIp:
      type: object
      required:
        - tenantId
        - subscriptionId
        - resourceGroupName
        - ipName
      properties:
        tenantId:
          type: string
          description: The tenant ID.
        subscriptionId:
          type: string
          description: The subscription ID.
        resourceGroupName:
          type: string
          description: Name of the resource group.
        ipName:
          type: string
          description: The user-provided name to identify the IP.
    AzureDisk:
      type: object
      required:
        - tenantId
        - subscriptionId
        - resourceGroupName
        - diskName
      properties:
        tenantId:
          type: string
          description: The tenant ID.
        subscriptionId:
          type: string
          description: The subscription ID.
        resourceGroupName:
          type: string
          description: Name of the resource group.
        diskName:
          type: string
          description: The user-provided name to identify the disk.
    AzureNetwork:
      type: object
      required:
        - tenantId
        - subscriptionId
        - resourceGroupName
        - networkName
      properties:
        tenantId:
          type: string
          description: The tenant ID.
        subscriptionId:
          type: string
          description: The subscription ID.
        resourceGroupName:
          type: string
          description: Name of the resource group.
        networkName:
          type: string
          description: The user-provided name to identify the network.
    AzureNetworkSecurityGroup:
      type: object
      required:
        - tenantId
        - subscriptionId
        - resourceGroupName
        - networkSecurityGroupName
      properties:
        tenantId:
          type: string
          description: The tenant ID.
        subscriptionId:
          type: string
          description: The subscription ID.
        resourceGroupName:
          type: string
          description: Name of the resource group.
        networkSecurityGroupName:
          type: string
          description: The user-provided name to identify the network security group.
    AzureVirtualMachine:
      type: object
      required:
        - tenantId
        - subscriptionId
        - resourceGroupName
        - vmName
      properties:
        tenantId:
          type: string
          description: The tenant ID.
        subscriptionId:
          type: string
          description: The subscription ID.
        resourceGroupName:
          type: string
          description: Name of the resource group.
        vmName:
          type: string
          description: The user-provided name to identify the VM.
    # A cloud resource unique identifier. Each CloudResourceUid represents exactly one cloud resource.
    # We are not doing polymorphism at this moment because of lack of support in swagger-codegen or openApiGenerator
    # Now CloudResourceUid contains all possible cloud resource types, and we will assume there is only one being set
    # when using this.
    CloudResourceUid:
      type: object
      properties:
        googleAiNotebookInstanceUid:
          $ref: '#/components/schemas/GoogleAiNotebookInstanceUid'
        googleBigQueryDatasetUid:
          $ref: '#/components/schemas/GoogleBigQueryDatasetUid'
        googleBigQueryTableUid:
          $ref: '#/components/schemas/GoogleBigQueryTableUid'
        googleBlobUid:
          $ref: '#/components/schemas/GoogleBlobUid'
        googleBucketUid:
          $ref: '#/components/schemas/GoogleBucketUid'
        googleProjectUid:
          $ref: '#/components/schemas/GoogleProjectUid'
        azurePublicIp:
          $ref: '#/components/schemas/AzurePublicIp'
        azureDisk:
          $ref: '#/components/schemas/AzureDisk'
        azureNetwork:
          $ref: '#/components/schemas/AzureNetwork'
        azureNetworkSecurityGroup:
          $ref: '#/components/schemas/AzureNetworkSecurityGroup'
        azureVirtualMachine:
          $ref: '#/components/schemas/AzureVirtualMachine'
