package bio.terra.cloudres.google.bigquery;

import bio.terra.cloudres.common.CloudOperation;

/** {@link CloudOperation} for using Google BigQuery API. */
public enum BigQueryOperation implements CloudOperation {
  GOOGLE_DELETE_BIGQUERY_DATASET,
  GOOGLE_GET_BIGQUERY_DATASET,
  GOOGLE_INSERT_BIGQUERY_DATASET,
  GOOGLE_LIST_BIGQUERY_DATASET,
  GOOGLE_PATCH_BIGQUERY_DATASET,
  GOOGLE_UPDATE_BIGQUERY_DATASET,
  GOOGLE_DELETE_BIGQUERY_TABLE,
  GOOGLE_GET_BIGQUERY_TABLE,
  GOOGLE_GET_IAM_POLICY_BIGQUERY_TABLE,
  GOOGLE_INSERT_BIGQUERY_TABLE,
  GOOGLE_LIST_BIGQUERY_TABLE,
  GOOGLE_PATCH_BIGQUERY_TABLE,
  GOOGLE_SET_IAM_POLICY_BIGQUERY_TABLE,
  GOOGLE_TEST_IAM_POLICY_BIGQUERY_TABLE,
  GOOGLE_UPDATE_BIGQUERY_TABLE;
}
