package bio.terra.cloudres.common;

/** The supported Cloud API methods in Enum */
public enum CloudOperation {
  // Google Resource Manager Operations
  GOOGLE_CREATE_PROJECT,
  GOOGLE_DELETE_PROJECT,
  GOOGLE_GET_PROJECT,
  GOOGLE_GET_IAM_POLICY_PROJECT,
  GOOGLE_SET_IAM_POLICY_PROJECT,
  GOOGLE_RESOURCE_MANAGER_OPERATION_GET,

  // Google Storage Operations
  GOOGLE_COPY_BLOB,
  GOOGLE_CREATE_ACL_BLOB,
  GOOGLE_CREATE_BLOB,
  GOOGLE_CREATE_BLOB_AND_WRITER,
  GOOGLE_CREATE_BUCKET,
  GOOGLE_GET_ACL_BLOB,
  GOOGLE_GET_BLOB,
  GOOGLE_LIST_BLOB,
  GOOGLE_GET_BUCKET,
  GOOGLE_DELETE_ACL_BLOB,
  GOOGLE_DELETE_BLOB,
  GOOGLE_DELETE_BUCKET,
  GOOGLE_READ_BLOB,
  GOOGLE_UPDATE_BUCKET,

  // Google BigQuery Operations
  GOOGLE_CREATE_DATASET,
  GOOGLE_CREATE_BIGQUERY_TABLE,
  GOOGLE_INSERT_BIGQUERY_TABLE,
  GOOGLE_UPDATE_DATASET,
  GOOGLE_UPDATE_BIGQUERY_TABLE,
  GOOGLE_DELETE_DATASET,
  GOOGLE_DELETE_BIGQUERY_TABLE,
  GOOGLE_GET_DATASET,
  GOOGLE_GET_BIGQUERY_TABLE,
  GOOGLE_LIST_BIGQUERY_TABLE,
  GOOGLE_QUERY_BIGQUERY_TABLE,
  GOOGLE_RELOAD_DATASET,
  GOOGLE_RELOAD_BIGQUERY_TABLE,

  // Google Billing Operations
  GOOGLE_GET_PROJECT_BILLING,
  GOOGLE_UPDATE_PROJECT_BILLING,

  // Google Service Usage Operations,
  GOOGLE_BATCH_ENABLE_SERVICES,
  GOOGLE_LIST_SERVICES,
  GOOGLE_SERVICE_USAGE_OPERATION_GET,

  // Google Compute Operations,
  GOOGLE_COMPUTE_GLOBAL_OPERATION_GET,
  GOOGLE_COMPUTE_REGION_OPERATION_GET,
  GOOGLE_INSERT_FIREWALL,
  GOOGLE_INSERT_NETWORK,
  GOOGLE_INSERT_ROUTE,
  GOOGLE_INSERT_SUBNETWORK,
  GOOGLE_GET_FIREWAL,
  GOOGLE_GET_NETWORK,
  GOOGLE_GET_ROUTE,
  GOOGLE_GET_SUBNETWORK,

  // Google DNS Operations,
  GOOGLE_DNS_CREATE_CHANGEE,
  GOOGLE_DNS_CREATE_ZONE,
  GOOGLE_DNS_GET_CHANGE,
  GOOGLE_DNS_GET_ZONE,
  GOOGLE_DNS_LIST_RESOURCE_RECORD_SETS,
}
