# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Pull Vault image
        run: docker pull vault:1.1.0
      - name: Get Vault token
        id: vault-token-step
        run: |
          VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault write -field token \
             auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
             secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
          echo ::set-output name=vault-token::$VAULT_TOKEN
          echo ::add-mask::$VAULT_TOKEN
      - name: Get Vault secrets
        id: vault-secret-step
        run: |
          GCR_EMAIL=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_TOKEN=${{ steps.vault-token-step.outputs.vault-token }}" \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault read -field client_email ${VAULT_PATH_CI})
          GCR_KEY=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_TOKEN=${{ steps.vault-token-step.outputs.vault-token }}" \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault read -format json -field data ${VAULT_PATH_CI} | base64)
          echo ::set-output name=gcr-email::$GCR_EMAIL
          echo ::add-mask::$GCR_EMAIL
          echo ::set-output name=gcr-key::$GCR_KEY
          echo ::add-mask::$GCR_KEY
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x minniekenny # skip minniekenny
      - name: Test
        run: ./gradlew test -x minniekenny
